### ISSUE TITLE
auth manager doesn't seem to understand sharkey

### ISSUE THREAD

**Issue by kindacozi** [vivlim/pillbug#92]
(specifically transfem.social in my case, although levallava.land seems to show the same error)
attempting to login to a sharkey instance errors out with
```
n: Unknown SNS
    at new n (https://pillbug.vivl.im/assets/auth-manager-DCUUtf97.js:7:114447)
    at https://pillbug.vivl.im/assets/auth-manager-DCUUtf97.js:7:118320
    at d (https://pillbug.vivl.im/assets/auth-manager-DCUUtf97.js:7:116132)
    at Object.next (https://pillbug.vivl.im/assets/auth-manager-DCUUtf97.js:7:115415)
    at u (https://pillbug.vivl.im/assets/auth-manager-DCUUtf97.js:7:114993)
```
in theory sharkey should work, since it says it has a mastodon-compatible api?

**Comment by vivlim** [comment]
ah, weird. i haven't tried pillbug with sharkey, i requested an account on transfem.social to test against.
